---
- hosts: all
  remote_user: root
  tasks:
    - name: Install required debs
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - unzip
        - curl
        - software-properties-common
        - build-essential
        - git

    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: /root/download.zip
        dest: /tmp
        remote_src: no

    - name: Disable dpkg fsync
      shell: echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io
      args: 
        creates: /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Install dirmngr
      apt:
        name: dirmngr
        state: present

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Add ethereum repo key
      apt_key:
        id: 1C52189C923F6CA9
        keyserver: keyserver.ubuntu.com

    - name: Add node repo key
      apt_key:
        id: 1655A0AB68576280
        keyserver: keyserver.ubuntu.com

    - name: Add node repo
      apt_repository:
        repo: deb http://ppa.launchpad.net/ethereum/ethereum/ubuntu xenial main
        state: present

    - name: Add node repo
      apt_repository:
        repo: deb https://deb.nodesource.com/node_8.x stretch main
        state: present

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true


    - name: Install required debs
      apt:
        name: "{{ item }}"
        state: present
      with_items: 
        - nodejs

